# Generated by Django 5.2.6 on 2025-09-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extrusoura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.IntegerField(verbose_name='RE')),
                ('Data', models.DateField(auto_now=True, verbose_name='Data')),
                ('turno', models.CharField(max_length=2, verbose_name='Turno')),
                ('maquina_rodando', models.IntegerField(verbose_name='Máquina Rodando')),
                ('maquina_disponivel', models.IntegerField(verbose_name='Máquina Disponível')),
                ('inicio', models.TimeField(verbose_name='Início')),
                ('fim', models.TimeField(verbose_name='Fim')),
                ('quantidade', models.BooleanField(verbose_name='Quantidade')),
                ('sem_impuresas', models.BooleanField(verbose_name='Sem Impurezas')),
                ('presença_de_outros', models.BooleanField(verbose_name='Presença de Outros')),
                ('presenca_de_outros2', models.BooleanField(verbose_name='Presença de Outros')),
                ('matertial_insuficiente', models.BooleanField(verbose_name='Material Insuficiente')),
                ('autonoma', models.BooleanField(verbose_name='Autônoma')),
                ('preventiva', models.BooleanField(verbose_name='Preventiva')),
                ('correntiva_Mecanica', models.BooleanField(verbose_name='Corretiva Mecânica')),
                ('correntiva_Eletrica', models.BooleanField(verbose_name='Corretiva Elétrica')),
                ('quebra', models.BooleanField(verbose_name='Quebra')),
                ('laminadora_parada', models.BooleanField(verbose_name='Laminadora Parada')),
                ('outros', models.BooleanField(verbose_name='Outros')),
                ('detalhamento', models.TextField(verbose_name='Detalhamento')),
            ],
        ),
    ]
