# Generated by Django 5.2.6 on 2025-09-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrusoura',
            name='autonoma',
            field=models.BooleanField(blank=True, null=True, verbose_name='Autônoma'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='correntiva_Eletrica',
            field=models.BooleanField(blank=True, null=True, verbose_name='Corretiva Elétrica'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='correntiva_Mecanica',
            field=models.BooleanField(blank=True, null=True, verbose_name='Corretiva Mecânica'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='laminadora_parada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Laminadora Parada'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='matertial_insuficiente',
            field=models.BooleanField(blank=True, null=True, verbose_name='Material Insuficiente'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='outros',
            field=models.BooleanField(blank=True, null=True, verbose_name='Outros'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='presenca_de_outros2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Presença de Outros'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='presença_de_outros',
            field=models.BooleanField(blank=True, null=True, verbose_name='Presença de Outros'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='preventiva',
            field=models.BooleanField(blank=True, null=True, verbose_name='Preventiva'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='quantidade',
            field=models.BooleanField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='quebra',
            field=models.BooleanField(blank=True, null=True, verbose_name='Quebra'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='sem_impuresas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sem Impurezas'),
        ),
    ]
