# Generated by Django 5.2.6 on 2025-09-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0002_alter_extrusoura_autonoma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrusoura',
            old_name='presença_de_outros',
            new_name='presenca_de_outros',
        ),
    ]
