# Generated by Django 5.2.6 on 2025-09-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0003_rename_presença_de_outros_extrusoura_presenca_de_outros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrusoura',
            name='autonoma',
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='correntiva_Eletrica',
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='correntiva_Mecanica',
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='presenca_de_outros',
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='presenca_de_outros2',
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='preventiva',
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='sem_impuresas',
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='detalhamento',
            field=models.CharField(max_length=1500, verbose_name='Detalhamento'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='inicio',
            field=models.TimeField(auto_now=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='maquina_disponivel',
            field=models.CharField(max_length=100, verbose_name='Máquina Disponível'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='maquina_rodando',
            field=models.CharField(max_length=100, verbose_name='Máquina Rodando'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='re',
            field=models.CharField(max_length=100, verbose_name='RE'),
        ),
    ]
