# Generated by Django 5.2.6 on 2025-09-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0004_remove_extrusoura_autonoma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrusoura',
            name='inicio',
            field=models.TimeField(verbose_name='Início'),
        ),
    ]
