# Generated by Django 5.2.6 on 2025-09-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0005_alter_extrusoura_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrusoura',
            name='maquina_disponivel',
            field=models.IntegerField(verbose_name='Máquina Disponível'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='maquina_rodando',
            field=models.IntegerField(verbose_name='Máquina Rodando'),
        ),
    ]
