# Generated by Django 5.2.6 on 2025-09-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0006_alter_extrusoura_maquina_disponivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrusoura',
            name='Data',
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='fim',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='inicio',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='maquina_disponivel',
            field=models.CharField(max_length=100, verbose_name='Máquina Disponível'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='maquina_rodando',
            field=models.CharField(max_length=100, verbose_name='Máquina Rodando'),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='turno',
            field=models.CharField(max_length=2),
        ),
        migrations.AddField(
            model_name='extrusoura',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
