# Generated by Django 5.2.6 on 2025-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0007_remove_extrusoura_data_alter_extrusoura_fim_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrusoura',
            options={'ordering': ['-data', '-inicio']},
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='extrusoura',
            name='quebra',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Quebra'),
        ),
    ]
