# Generated by Django 5.2.6 on 2025-09-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0008_alter_extrusoura_options_alter_extrusoura_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrusoura',
            name='quebra',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Quebra'),
        ),
    ]
