# Generated by Django 5.2.6 on 2025-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0009_alter_extrusoura_quebra'),
    ]

    operations = [
        migrations.CreateModel(
            name='AguaExtrusoura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.CharField(max_length=100, verbose_name='RE')),
                ('data', models.DateField(auto_now_add=True)),
                ('turno', models.CharField(max_length=2)),
                ('cloro', models.FloatField()),
                ('turbidez', models.FloatField()),
                ('horario', models.TimeField(auto_now=True)),
                ('observacao', models.CharField(max_length=1500, verbose_name='Observação')),
            ],
        ),
    ]
