# Generated by Django 5.2.6 on 2025-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0010_aguaextrusoura'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.CharField(max_length=100, verbose_name='RE')),
                ('data', models.DateField(auto_now_add=True)),
                ('turno', models.CharField(max_length=2)),
                ('fardo_virgem', models.IntegerField()),
                ('fardo_laminado', models.IntegerField()),
                ('fardo_total', models.IntegerField(default=0, editable=False)),
                ('reversao', models.IntegerField()),
                ('observacao', models.CharField(max_length=1500, verbose_name='Observação')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aguaextrusoura',
            options={'ordering': ['-data', '-horario']},
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='laminadora_parada',
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='matertial_insuficiente',
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='outros',
        ),
        migrations.RemoveField(
            model_name='extrusoura',
            name='quebra',
        ),
    ]
